language: java

jdk:
  - openjdk8

service:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS submissionsdb;"

before_script: mvn install -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)
