# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest,ubuntu-20.04, windows-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 18
#    - uses: actions/checkout@v3
#    - uses: actions/setup-java@v3
#      with:
#        distribution: 'liberica'
#        java-version: '8'
#        java-package: 'jdk+fx'
#         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#         settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Install with Maven
      run:  mvn -B package --file pom.xml

    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
       name: Package
       path: staging
